- hosts: localhost
  connection: local
  vars:
    base_path: ../../content
    source: /modules/ROOT/
    destination: output

  tasks:
  - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
    ansible.builtin.replace:
      path: "{{ base_path }}{{ source }}pages/user_information.adoc"
      regexp: ^([%]).*\1$'
      replace: "{{ lookup('env', 'guid') }}" 
    register: replace
  - debug: msg="{{ replace }}"

  - name: Run asciidoctor for adoc and txt files
    shell: (cd "{{ base_path }}"; asciidoctor -b html5 -R "{{ source }}" --destination-dir "{{ destination }}" '**/*.adoc')
    register: doc
  - debug: msg="{{ doc.stdout }}"

